# ===== APPLICATION =====
spring.application.name=pap

# ===== DATASOURCE (PostgreSQL) =====
spring.datasource.url=jdbc:postgresql://localhost:5432/pap_db
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== LOGS =====
logging.level.org.springframework.security=DEBUG
logging.level.com.leoni.pap=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===== CHEMINS UPLOAD =====
upload.path=./uploads/defauts
certificates.path=./certificates
# ===== CHEMINS RAPPORTS (chemins ABSOLUS pour fiabilit?) =====
upload.rapport.path=C:/Users/zaine/OneDrive/Bureau/dev/pap/uploads/rapports-audit
leoni.upload.rapport-importe=C:/Users/zaine/OneDrive/Bureau/dev/pap/uploads/rapports-audit
leoni.upload.rapport-final=C:/Users/zaine/OneDrive/Bureau/dev/pap/uploads/rapport
leoni.upload.pdf-correctifs=C:/Users/zaine/OneDrive/Bureau/dev/pap/uploads/pdfs-correctifs

# ===== ? NOUVEAU ? CERTIFICATS AUDITEUR IMPORTÉS =====
upload.certificat-auditeur.path=./uploads/certificats-auditeur

# Durée de validité d'un certificat importé, EN MINUTES.
# Production : 1051200 = 2 ans (2 x 365 x 24 x 60).
# Pour TESTER rapidement l'expiration, remplacer temporairement par une
# petite valeur, ex: 5 (= 5 minutes), puis remettre 1051200 une fois testé.
certificat.auditeur.duree-validite-minutes=1051200

# Délai d'alerte avant expiration, EN MINUTES.
# Production : 10080 = 7 jours (7 x 24 x 60).
# Pour TESTER : remplacer temporairement par ex. 2 (= 2 minutes), puis
# remettre 10080 une fois testé.
certificat.auditeur.notif-avant-expiration-minutes=10080

# ===== STATIC RESOURCES =====
spring.web.resources.static-locations=file:./uploads/,classpath:/static/
spring.mvc.static-path-pattern=/uploads/**
spring.security.headers.frame-options=disable

# ===== MULTIPART UPLOAD =====
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ===== EMAIL SMTP =====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=zainebhamouda13@gmail.com
spring.mail.password=yejgropleoimsdyd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

# ===== URLs =====
# IMPORTANT : utiliser localhost quand frontend et backend tournent sur la meme machine
app.frontend.url=http://localhost:5173
app.backend.url=http://localhost:8080

# ===== OUTILS EXTERNES =====
tesseract.path=C:/Program Files/Tesseract-OCR/tesseract.exe
tesseract.lang=fra+eng+deu
ia.api.url=http://localhost:5000

server.address=0.0.0.0